variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
  stableNodeVersion: "12.x"
  currentNodeVersion: "14.x"
  # Used with `eslintVersion` to see if `spec:e2e` and `benchmarks` should run
  e2eEslintVersion: "eslint@7.3.1"

strategy:
  matrix:
    linux_node_stable_eslint5:
      imageName: "ubuntu-16.04"
      nodeVersion: $(stableNodeVersion)
      eslintVersion: "eslint@^5"
    linux_node_stable_eslint6:
      imageName: "ubuntu-16.04"
      nodeVersion: $(stableNodeVersion)
      eslintVersion: "eslint@^6"
    linux_node_stable_eslint7:
      imageName: "ubuntu-16.04"
      nodeVersion: $(stableNodeVersion)
      eslintVersion: "eslint@7.3.1"
    linux_node_current_eslint5:
      imageName: "ubuntu-16.04"
      nodeVersion: $(currentNodeVersion)
      eslintVersion: "eslint@^5"
    linux_node_current_eslint6:
      imageName: "ubuntu-16.04"
      nodeVersion: $(currentNodeVersion)
      eslintVersion: "eslint@^6"
    linux_node_current_eslint7:
      imageName: "ubuntu-16.04"
      nodeVersion: $(currentNodeVersion)
      eslintVersion: "eslint@7.3.1"
    mac_node_stable_eslint5:
      imageName: "macos-10.14"
      nodeVersion: $(stableNodeVersion)
      eslintVersion: "eslint@^5"
    mac_node_stable_eslint6:
      imageName: "macos-10.14"
      nodeVersion: $(stableNodeVersion)
      eslintVersion: "eslint@^6"
    mac_node_stable_eslint7:
      imageName: "macos-10.14"
      nodeVersion: $(stableNodeVersion)
      eslintVersion: "eslint@7.3.1"
    mac_node_current_eslint5:
      imageName: "macos-10.14"
      nodeVersion: $(currentNodeVersion)
      eslintVersion: "eslint@^5"
    mac_node_current_eslint6:
      imageName: "macos-10.14"
      nodeVersion: $(currentNodeVersion)
      eslintVersion: "eslint@^6"
    mac_node_current_eslint7:
      imageName: "macos-10.14"
      nodeVersion: $(currentNodeVersion)
      eslintVersion: "eslint@7.3.1"
    windows_node_stable_eslint5:
      imageName: "vs2017-win2016"
      nodeVersion: $(stableNodeVersion)
      eslintVersion: "eslint@^5"
    windows_node_stable_eslint6:
      imageName: "vs2017-win2016"
      nodeVersion: $(stableNodeVersion)
      eslintVersion: "eslint@^6"
    windows_node_stable_eslint7:
      imageName: "vs2017-win2016"
      nodeVersion: $(stableNodeVersion)
      eslintVersion: "eslint@7.3.1"
    windows_node_current_eslint5:
      imageName: "vs2017-win2016"
      nodeVersion: $(currentNodeVersion)
      eslintVersion: "eslint@^5"
    windows_node_current_eslint6:
      imageName: "vs2017-win2016"
      nodeVersion: $(currentNodeVersion)
      eslintVersion: "eslint@^6"
    windows_node_current_eslint7:
      imageName: "vs2017-win2016"
      nodeVersion: $(currentNodeVersion)
      eslintVersion: "eslint@7.3.1"

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(nodeVersion)
    displayName: Install node@$(nodeVersion)
  - task: Cache@2
    inputs:
      key: 'yarn | "$(Agent.OS)" | yarn.lock'
      restoreKeys: |
        yarn | "$(Agent.OS)"
        yarn
      path: $(YARN_CACHE_FOLDER)
    displayName: Cache Yarn packages
  - script: yarn --frozen-lockfile && yarn add --dev $(eslintVersion) && yarn test
    displayName: Install dependencies and run yarn test
  # E2E tests use eslint@7+ only feature (the Node.js API class ESLint)
  # Also disabled on windows because of jest snapshot problems
  - script: yarn spec:e2e
    condition: and(eq(variables['eslintVersion'], variables['e2eEslintVersion']), ne(variables['imageName'], 'vs2017-win2016'))
    displayName: Run yarn spec:e2e if $(eslintVersion)==$(e2eEslintVersion)
  # Benchmarks use eslint@7_ only feature (the Node.js API class ESLint)
  - script: yarn benchmarks
    condition: eq(variables['eslintVersion'], variables['e2eEslintVersion'])
    displayName: Run yarn benchmarks if $(eslintVersion)==$(e2eEslintVersion)
  # Upload Jest code coverage
  - script: yarn spec --coverage --coverageReporters=cobertura
    displayName: Generate Jest coverage report
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml
